server:
  port: 8080
  servlet:
    context-path: /radar

service:
  wx:
    url: https://api.weixin.qq.com/
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/radar?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: root
    url: jdbc:mysql://47.93.189.30:3306/radar?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: hn_tes
    password: bugu2019!@#$%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: betaHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
